replicaCount: 1
image:
  useImagePullSecrets: false
  pullPolicy: Always
service:
  internalPort: 80
  externalPort: 80
ingress:
  enabled: true
  basedomain: c8341eb32c8b4e7ab260.eastus.aksapp.io # replace with your own from the portal
